language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
      # Build tags that match this regex in addition to building the master branch.
    - /^v[0-9]+\.[0-9]+/

after_success:
  - test "${TRAVIS_JDK_VERSION}" == "oraclejdk8" && ./gradlew -s jacocoTestReport coveralls
